@token = Bearer e8f3dd16bde8a409eb91587e8aa0616507357507
@wegpiraatId = 5ad209fe47441f0b90672f77

POST http://localhost:3000/api/wegpiraten/{{wegpiraatId}}/comment HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
	"commentData": "I commented something"
}