@token = Bearer e3b943f0ca5213e8ef24235754298d417c7ec116
@wegpiraatId = 5a774006452f7548a82daf5f

POST http://localhost:3000/api/wegpiraten/{{wegpiraatId}}/comment HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
	"commentData": "I commented something"
}