@token = Bearer b1d49c5debbc6df41902e90567efd3c5eed27790
@wegpiraatId = 5ad209fe47441f0b90672f77
POST http://localhost:3000/api/wegpiraten/{{wegpiraatId}}/like HTTP/1.1
Content-Type: application/json
Authorization: {{token}}