@token = Bearer 8de85e2cfee34831f9708791f93a40ad4800d370

POST http://localhost:3000/api/wegpiraten HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
	"title": "kekekek",
	"description": "kekkeke",
	"picture": "kekekek"
}