@token = Bearer 0c1dd9c57340b38e825ab0720b4b8737640f6515

POST http://localhost:3000/api/wegpiraten HTTP/1.1
Content-Type: multipart/form-data
Authorization: {{token}}

{
	"title": "kekekek",
	"description": "kekkeke",
	"picture": "kekekek"
}