@token = Bearer bff80c0e7ca9e672cdbc68d7e184a18881043502

POST http://localhost:3000/api/wegpiraten HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
	"title": "kekekek",
	"description": "kekkeke",
	"pictaure": "kekekek"
}