POST http://localhost:3000/api/password/forgot/confirm HTTP/1.1
Content-Type: application/json

{
	"email":"kenan.ekici@outlook.com",
    "token":"d20529868dacf03c",
    "password": "example123",
    "confirm": "example123"
}