@token = Bearer cc76d0cc2fcc242bfec7d3c849d810edc686acba

POST https://kenan-api.herokuapp.com/api/wegpiraten/arr HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
	"idArr":["5abbe4c0418f9b2a10c33fb3", "5ac017725d06622d4cc3259b"]
}