@username= kenan.ekici@outlook.com
@password= kenan123
@clientid= wegpiraat
@secret= 123

POST https://kenan-api.herokuapp.com/api/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{password}}&grant_type=password&client_id={{clientid}}&client_secret={{secret}}
