@token = 50fc1333a92f897f1feb680af3cec04ee3d275d7
@clientid= wegpiraat
@secret= 123
POST http://localhost:3000/api/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token&refresh_token={{token}}&client_id={{clientid}}&client_secret={{secret}}
