@token = Bearer 9f34754b047effeadbb188304577c6bb4fa18801
POST http://localhost:3000/api/password/reset HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
	"password":"example",
    "confirm":"example"
}